version: '3'

services:
  checkbook:
    image: checkbook-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'checkbook-api'
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./:/app:rw
    ports:
      - "8000:80"