version: '3'

services:
  checkbook:
    image: docker.io/library/checkbook
    container_name: 'checkbook'
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./:/app:rw
    ports:
      - "8000:80"